services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: "8G"
    security_opt:
      - no-new-privileges
    cap_drop:
      - all
    cap_add:
      - SYS_NICE
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - openwebui
      - offline_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3333:8080"
    volumes:
      - open-webui-podman:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    networks:
      - openwebui

volumes:
  ollama:
  open-webui-podman:

networks:
  openwebui:
    name: openwebui
    driver: bridge

  offline_network:
    driver: bridge
    # driver_opts:
    #   com.docker.network.bridge.enable_ip_masquerade: "${ONLINE}"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
