version: '3'

services:
  mysql:
    image: mysql/mysql-server:latest-aarch64
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
