version: "3.0"

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate
    restart: always
    ports:
      - "5000:5000"

  spiderfoot:
    volumes:
      - spiderfoot-data:/var/lib/spiderfoot
    image: dtagdevsec/spiderfoot
    container_name: spiderfoot
    ports:
      - "5001:5001"
    restart: unless-stopped

volumes:
  spiderfoot-data:
