services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5100:5000"
    restart: unless-stopped
    networks:
      - libretranslate

  spiderfoot:
    image: ctdc/spiderfoot
    container_name: spiderfoot
    volumes:
      - spiderfoot-data:/var/lib/spiderfoot
    ports:
      - "5200:5001"
    restart: unless-stopped
    networks:
      - spiderfoot

  cyberchef:
    image: ghcr.io/gchq/cyberchef
    container_name: cyberchef
    ports:
      - "5300:80"
    restart: unless-stopped
    networks:
      - cyberchef

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "9000:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    networks:
      - openwebui

volumes:
  spiderfoot-data:
  open-webui:

networks:
  libretranslate:
    name: libretranslate
    driver: bridge
  spiderfoot:
    name: spiderfoot
    driver: bridge
  cyberchef:
    name: cyberchef
    driver: bridge
  openwebui:
    name: openwebui
    driver: bridge
